### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by rutchkiwi** [gettyimages/spray-swagger#57]
Hey! 

Thanks for making this tool, really useful!

I was wondering if there is any support for enabling CORS for the swagger route? At the company I work at we want to host the swagger-ui on a different server than the one serving the api-docs json, which does not work right now as CORS is not enabled for the api-docs resource. For my purposes it would be enough to simply set Access-Control-Allow-Origin=*

Thanks!

**Comment by mhamrah** [comment]
We should probably support this out-of-box, but CORS can be tricky with regards to how much you actually want to open.  This seems to be the "nicest" implementation after some quick googling: https://gist.github.com/ayosec/4324747.

It's really just about wrapping the spray-swagger route with the appropriate ```respondWithHeaders``` calls that you want/need.

**Comment by rutchkiwi** [comment]
ok, wrapping the route was simpler than I though, especially in my case when I only added the basic Access-Control-Allow-Origin=*

Thanks! :)
